name: Simple CI/CD (Docker Hub)

on:
  push:
    branches:
      - dev
      - main
  schedule:
    - cron: '30 14 * * 4'   # Every Friday at 2 PM IST
  workflow_dispatch:    

jobs:

# =====================
# BUILD DEV IMAGE
# =====================
  build-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image (DEV)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:dev-${{ github.run_id }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:dev-${{ github.run_id }}

# =====================
# DEPLOY DEV
# =====================
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    needs: build-dev
    runs-on: self-hosted

    steps:
      - name: Deploy DEV
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:dev-${{ github.run_id }}

# =====================
# BUILD MAIN IMAGE
# =====================
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login \
            -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image (MAIN)
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-app:main-${{ github.run_id }} .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-app:main-${{ github.run_id }}

# =====================
# DEPLOY MAIN
# =====================
  deploy-main:
    if: github.ref == 'refs/heads/main'
    needs: build-main
    runs-on: self-hosted

    steps:
      - name: Deploy MAIN
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-app:main-${{ github.run_id }}

